version: '2'
networks:
  # To create this network in your local host
  # docker network create -d bridge --subnet 192.168.0.0/24 --gateway 192.168.0.1 docker-localhost
  # Then use 192.168.0.1 as the IP of your localhost in order to access, for example, the MySQL running in your
  # local PC
  docker-localhost:
    external: true
services:
  authenticate-app:
    image: authenticate
    environment:
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_DATASOURCE_URL=jdbc:mysql://192.168.0.1:3306/authenticate?useUnicode=true&characterEncoding=utf8&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - JHIPSTER_SLEEP=30
      - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
      - JHIPSTER_REGISTRY_PASSWORD=admin
      - _JAVA_OPTIONS=-Djava.net.preferIPv4Stack=true
      - VIRTUAL_HOST=authenticate.local
    networks:
      - docker-localhost

  gateway-app:
    image: gateway
    environment:
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_DATASOURCE_URL=jdbc:mysql://192.168.0.1:3306/gateway?useUnicode=true&characterEncoding=utf8&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - JHIPSTER_SLEEP=30
      - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
      - JHIPSTER_REGISTRY_PASSWORD=admin
      - JAVA_OPTS=-Xmx1024m -Xms512m
      - _JAVA_OPTIONS=-Xmx1024m -Xms512m
      - VIRTUAL_HOST=gateway.local
    networks:
      - docker-localhost
    ports:
      - 8080:8080

  nginx:
    image: nginx:1.13-alpine
    volumes:
      - ../billing.web/build/www:/usr/share/nginx/html
      - ../billing.web/site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8092:8092
    networks:
      - docker-localhost
  elasticsearch:
    image: elasticsearch:2.4.6
    environment:
      - JAVA_OPTS=-Xmx1024m -Xms512m
      - _JAVA_OPTIONS=-Xmx1024m -Xms512m
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - docker-localhost

  jhipster-registry:
    extends:
      file: jhipster-registry.yml
      service: jhipster-registry
    networks:
      - docker-localhost